### PR TITLE
Add metadata to the JSON payload.

### PR DESCRIPTION
**Pull request by aweiker**
This allows additional data to be passed in the log message.

### CODE REVIEW

**Comment by aweiker** [comment]
@svetob I just wanted to follow up to see if this was an addition that you are welcome to?

**Comment by vorce** [comment]
Hmm this looks interesting

**Comment by svetob** [comment]
Hi, sorry @aweiker that I have completely missed this PR until now!

We definitely should include the metadata, so kudos for this PR. Going to do some quick tests before merging.

**Comment by svetob** [comment]
This is a clear improvement on the current behaviour, so i'm going to merge+release this. After that I think we should:

- Remove the "metadata" configuration option. I see no reason not to include all the metadata items sent by the user.
- Potentially put the metadata keys at root level of the message, as opposed to as a map under the "metadata" key. This may make it more useful in Kibana, but need to test both behaviours first to make sure.

**Pull request merged**
