### PR TITLE
Formatter option

### PR DESCRIPTION
**Pull request by bmoe**
Does this look close to reasonable?
One thing I don't know how to handle is a bad configuration option.  Is there a community standard or convention for that?  Crash?  Log and move on with a valid default?

### CODE REVIEW

**Comment by bmoe** [comment]
Neat that it failed on the FIXME.  I didn't expect you to merge, but I wanted you to be able to easilyl see what I was doing.

**Comment by svetob** [comment]
Hi, happy to see you're finding this useful, and thanks for the PR!

At first glance this looks good. I'll need to take a closer look before merging, however it's still holidays here so it could take a few days before I can do that. Hope this doesn't cause you problems until then.

**Comment by bmoe** [comment]
Thanks.  No rush.  Am not inconvenienced at all.  Enjoy your holidays!

**Comment by svetob** [comment]
Ok, this looks good, thanks @bmoe ! My only request is if we can add the same formatter functionality to the console backend as well, to keep the console and TCP logs consistent.

**Comment by bmoe** [comment]
Excellent.  I'll put formatter into the console backend in the next couple of days.  Thanks.

**Pull request merged**
